import React, {useEffect, useState} from 'react'; import {createRoot} from 'react-dom/client'; import './styles.css';
const API='http://localhost:8080/api/v1';
type Row={employeeNumber:string;fullName:string;department:string;country:string;annualBaseSalary:number;currency:string}; type Page={content:Row[];totalElements:number};
async function json(path:string, options?:RequestInit){const r=await fetch(API+path,options);if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail);return r.json()}
function App(){const [page,setPage]=useState<Page>({content:[],totalElements:0}),[search,setSearch]=useState(''),[country,setCountry]=useState(''),[analytics,setAnalytics]=useState<any>(),[selected,setSelected]=useState<any>(),[error,setError]=useState('');
 const load=()=>json(`/employees?size=25&search=${encodeURIComponent(search)}&country=${encodeURIComponent(country)}`).then(setPage).catch(e=>setError(e.message));
 useEffect(()=>{load();json(`/analytics${country?`?country=${country}`:''}`).then(setAnalytics).catch(e=>setError(e.message))},[country]);
 const open=(n:string)=>json(`/employees/${n}`).then(setSelected).catch(e=>setError(e.message));
 const save=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{setSelected(await json(`/employees/${selected.employeeNumber}/compensation`,{method:'PUT',headers:{'Content-Type':'application/json','X-Actor':'hr.manager'},body:JSON.stringify({annualBaseSalary:Number(f.get('salary')),bonusTargetPercent:Number(f.get('bonus')),currency:f.get('currency'),effectiveDate:f.get('date'),expectedVersion:selected.compensation.version})}));load()}catch(e:any){setError(e.message)}};
 return <main><header><div><h1>ACME Salary Management</h1><p>Compensation workspace for HR</p></div><button onClick={load}>Refresh directory</button></header>{error&&<p className="error">{error}</p>}<section className="cards">{analytics?.currencies.map((x:any)=><article key={x.currency}><b>{x.currency} payroll</b><strong>{x.headcount.toLocaleString()} people</strong><span>Median {x.medianAnnualBaseSalary.toLocaleString()} {x.currency}</span></article>)}</section><section className="toolbar"><input aria-label="Search employees" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name or employee number"/><select value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option><option>US</option><option>IN</option><option>GB</option><option>DE</option><option>SG</option><option>AU</option></select><button onClick={load}>Search</button><span>{page.totalElements.toLocaleString()} employees</span></section><table><thead><tr><th>Employee</th><th>Department</th><th>Country</th><th>Annual base</th></tr></thead><tbody>{page.content.map(x=><tr key={x.employeeNumber} onClick={()=>open(x.employeeNumber)}><td>{x.fullName}<small>{x.employeeNumber}</small></td><td>{x.department}</td><td>{x.country}</td><td>{x.annualBaseSalary.toLocaleString()} {x.currency}</td></tr>)}</tbody></table>{selected&&<aside><button className="close" onClick={()=>setSelected(null)}>×</button><h2>{selected.firstName} {selected.lastName}</h2><p>{selected.jobTitle} · {selected.department} · {selected.country}</p><form onSubmit={save}><label>Annual base<input name="salary" type="number" min="0" step="0.01" defaultValue={selected.compensation.annualBaseSalary}/></label><label>Bonus target %<input name="bonus" type="number" min="0" max="100" defaultValue={selected.compensation.bonusTargetPercent}/></label><label>Currency<input name="currency" pattern="[A-Z]{3}" defaultValue={selected.compensation.currency}/></label><label>Effective date<input name="date" type="date" defaultValue={selected.compensation.effectiveDate}/></label><button>Save compensation</button></form><h3>Change history</h3>{selected.salaryHistory.length?<ul>{selected.salaryHistory.map((x:any,i:number)=><li key={i}>{x.previousBaseSalary} → {x.newBaseSalary} {x.currency} by {x.changedBy}</li>)}</ul>:<p>No salary changes recorded.</p>}</aside>}</main>}; createRoot(document.getElementById('root')!).render(<App/>);
