spring:
  application:
    name: salary-management-api
  datasource:
    url: jdbc:sqlite:data/salary-management.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true

app:
  seed:
    enabled: true
